### ISSUE TITLE
「八哥」：台/國語夾雜分段問題

### ISSUE THREAD

**Issue by audreyt** [g0v/koktai#4]
目前的[解析結構](https://g0v.github.io/koktai/01.html)如下：

<img width="550" alt="screen shot 2015-11-26 at 1 57 28 pm" src="https://cloud.githubusercontent.com/assets/20723/11416145/d6b439de-9445-11e5-80aa-c2852dc483d3.png">

在 WikiSource 的[目標排版](https://zh.wikisource.org/wiki/%E5%9C%8B%E8%87%BA%E5%B0%8D%E7%85%A7%E6%B4%BB%E7%94%A8%E8%BE%AD%E5%85%B8/%E3%84%85%E3%84%9A#.E5.85.AB.EF.BC.88.E3.84.85.E3.84.9A.EF.BC.89.E5.93.A5.EF.BC.88.E3.84.8D.E3.84.9C.EF.BC.89)如下：

<img width="364" alt="screen shot 2015-11-26 at 1 57 33 pm" src="https://cloud.githubusercontent.com/assets/20723/11416148/ddb5c752-9445-11e5-9b9f-bbce9d2d9f34.png">

可以看到「又，鳥名，～兒。又名鴝鵒。」應該是國語段落，不是台語的。

**Comment by a-tsioh** [comment]
fixed in 4d07838
