### ISSUE TITLE
吳守禮姓名台語拼音修正

### ISSUE THREAD

**Issue by MGdesigner** [g0v/koktai#8]
阿石很不好意思請你幫這個忙：請把README.md 檔裡面，吳守禮的台語拼音從" Ngo ShuLeh" 改成"Ngo Shiu Le" ，他兒子吳昭新醫生希望用這樣的拼音法。

**Comment by sih4sing5hong5** [comment]
@MGdesigner 我先直接改，毋過你也有權限改的樣子？

**Comment by MGdesigner** [comment]
sry，我忙亂到忘掉了，真的有耶 XD
